# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 20

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 40

[[main]]
  name = "Awards"
  url = "/awards"
  weight = 50

[[main]]
  name = "Scientific community"
  url = "/community"
  weight = 52

  [[main]]
  name = "Experience"
  url = "/experience"
  weight = 55

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 80

[[main]]
    name = "More"
    identifier = "more"
    weight = 100

[[main]]
  name = "News"
  parent = "more"
  url = "/news"
  weight = 1

[[main]]
  name = "Press"
  parent = "more"
  url = "/press"
  weight = 2

#[[main]]
#  name = "More Projects"
#  parent = "more"
#  url = "/project"
#  weight = 3

[[main]]
  name = "Posts"
  parent = "more"
  url = "/post"
  weight = 4

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
#[[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 100
